### ISSUE TITLE
Boost Download Error

### ISSUE THREAD

**Issue by ManojLII** [usnistgov/REFPROP-manager#12]
I am facing an issue while downloading the boost libraries.  I have installed VS 2022 and 2017 in my machine.

-- Fetching Boost
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Creating directories for 'boost-populate'
  Building Custom Rule C:/Users/ma4658/REFPROP-manager/build/_deps/boost-subbuild/CMakeLists.txt
  Performing download step (download, verify and extract) for 'boost-populate'
  -- Downloading...
     dst='C:/Users/ma4658/REFPROP-manager/build/_deps/boost-subbuild/boost-populate-prefix/src/boost_1_71_0.tar.bz2'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.tar.bz2'
  CMake Error at boost-subbuild/boost-populate-prefix/src/boost-populate-stamp/download-boost-populate.cmake:170 (message):
    Each download failed!

CUSTOMBUILD : error : downloading 'https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.tar.bz2' failed [C:\Users\ma4658\REFPROP-manager\build\_deps\boost-subbuild\boost-populate.vcxproj]
            status_code: 35
            status_string: "SSL connect error"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 35.165.207.58:443...

    Connected to boostorg.jfrog.io (35.165.207.58) port 443 (#0)

    schannel: disabled automatic use of client certificate

    ALPN: offers h2

    ALPN: offers http/1.1

    schannel: failed to receive handshake, SSL/TLS connection failed

    Closing connection 0

            --- LOG END ---

**Comment by ianhbell** [comment]
The download works for me. Try again in an hour and see if you have the same problem.
