### ISSUE TITLE
Call manager class

### ISSUE THREAD

**Issue by zhaolongjun** [usnistgov/REFPROP-manager#2]
I want to know how to call the manager class to run in parallel by C++(QT qmake), can you give me a test? 

I found the manager class test folder is empty, can you check it?

What's the difference between
``` C++
SETUPdll(nc,hfld,hhmx,href,ierr,herr,10000,255,3,255)
```
in REFPROP and 
``` C++
SETUPdll(handle, &handle_errcode, nc, hfld, hhmx, href, ierr, herr, 10000, 255, 3, 255)
```
 in manager?

**Comment by ianhbell** [comment]
I refactored the manager to allow for tests, and pushed my changes: https://github.com/usnistgov/REFPROP-manager/commit/5177af199d853cc8c2081ea99c8e9a2b9a8b65f4

**Comment by ianhbell** [comment]
In the methods of the manager, you always pass the handle to the instance you have acquired, as well as an error code (``handle_errcode``) that you should check after each call (0: good, !0: bad)

**Comment by zhaolongjun** [comment]
What REFPROP-manager/REFPROP-manager.hpp means? How does the manager  load multiple copies of the REFPROP dll into memory ? Does it run in parallel?

**Comment by zhaolongjun** [comment]
What REFPROP-manager/REFPROP-manager.hpp mean? What does handle_errcode return 1 mean? How to Call the manager class with C++11 to run in  paralle，can you give me a small example ？

**Comment by zhaolongjun** [comment]
What REFPROP-manager/REFPROP-manager.hpp mean? What does handle_errcode return 1 mean? How to Call the manager class with C++11 to run in paralle，can you give me a small example ？

**Comment by zhaolongjun** [comment]
Is only Python wrapper currently able to call this manager class? Can C + + be used for parallel invocation? Can you give me an example?

**Comment by ianhbell** [comment]
Please see https://github.com/usnistgov/REFPROP-manager#in-c11

**Comment by ianhbell** [comment]
The example in test/test2.cpp is much more comprehensive now, and can yield nearly linear speedup.

**Comment by zhaolongjun** [comment]
I complied errer! Have you tested it? Could you try again?


 
---Original---

**Comment by ianhbell** [comment]
Indeed I did, on linux in this case.  What error do you get?

**Comment by zhaolongjun** [comment]
On windows, gcc. 
When complie  REFFPROPInstance inn(),can't  find  dll.  I don't know  whether it  is  due  to dll path. 






------------------ 原始邮件 ------------------
发件人: "Ian Bell"<notifications@github.com>;
发送时间: 2019年6月6日(星期四) 晚上10:13
收件人: "usnistgov/REFPROP-manager"<REFPROP-manager@noreply.github.com>;
抄送: "Jun"<3224675587@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [usnistgov/REFPROP-manager] Call manager class (#2)



Indeed I did, on linux in this case.  What error do you get?

**Comment by ianhbell** [comment]
You are building the whole example with cmake, right?  That’s mandatory to make sure all the dependencies are handled correctly.

Can you please show the entire set of command-line calls you used (input and output)?  Without that its impossible to know where the problem lies.
