### ISSUE TITLE
Error Compiling REFPROP Manager

### ISSUE THREAD

**Issue by pmiquelm** [usnistgov/REFPROP-manager#3]
Good Evening,

I'm having issues compiling the manager from source. I am running on MacOS, 10.14.3. The compilation fails after this line:

`[ 66%] Building CXX object CMakeFiles/refpropmanager.dir/src/manager.cpp.o`

I have many warnings that seem to relate to the fact that it uses C++11, such as:

`/Users/Pau/REFPROP-manager/include/REFPROP-manager/REFPROP-manager.hpp:16:46: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
    virtual const char* what() const throw() override {
`

I believe these shouldn't be an issue, but I'm not sure. However, I also have several errors, such as:

`/Users/Pau/REFPROP-manager/include/REFPROP-manager/REFPROP-manager.hpp:12:7: error: exception specification of overriding function is more lax than base version
class InvalidHandle : public std::exception {`

and

`/Users/Pau/REFPROP-manager/externals/manyso/include/manyso/abc.h:45:10: error: no template named 'tuple' in namespace 'std'
    std::tuple<bool, load_method> is_locked() { `

The build finally fails with the follwoing message:

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
357 warnings and 20 errors generated.
CMakeFiles/refpropmanager.dir/build.make:62: recipe for target 'CMakeFiles/refpropmanager.dir/src/manager.cpp.o' failed
make[2]: *** [CMakeFiles/refpropmanager.dir/src/manager.cpp.o] Error 1
CMakeFiles/Makefile2:73: recipe for target 'CMakeFiles/refpropmanager.dir/all' failed
make[1]: *** [CMakeFiles/refpropmanager.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

I thought the issue was with my compiler, so I tried several ones, including gcc and g++, clang and clang++, as well as the default compilers MacOS uses. Furthermore, these errors occured using the normal UNIX build generator system, I tried using the Xcode generator, and got the following, different, error:

`/Users/Pau/REFPROP-manager/externals/manyso/externals/MemoryModule/MemoryModule.c:33:10: fatal error: 'windows.h' file not found
#include <windows.h>`

which is bizarre as I'm running on Mac. Do you have any idea where I may have made a mistake, or other options I can try? Thanks in advance for your help.

Pau

**Comment by ianhbell** [comment]
Interesting. I have to say that I have thus far only compiled the manager on windows and linux, but not OSX.  Looks like there are one or two issues to resolve with compilation.  Luckily I have an OSX computer, so I am sure I can get them fixed.  I’ll try to do so on Monday or Tuesday.

**Comment by ianhbell** [comment]
So....  it seems like I should not have been so confident. I have fixed one family of compilation issues by setting the C++ standard to 11, and fixing one or two C++11 bugs.  But the pristine loading of the DLL/.dylib is evidently just not possible on OSX.  Or at least that's what this issue suggests: https://stackoverflow.com/questions/17725752/load-dynamic-library-with-new-link-list-map-on-mac-os-x

**Comment by pmiquelm** [comment]
Ah, I see. Is that just an inherent issue with OSX then? Interestingly, I just tried to compile it on a Linux server, and I got a similar error:

```
[ 71%] Building CXX object CMakeFiles/refpropmanager.dir/src/manager.cpp.o
/home/pmm1g15/REFPROP-manager/src/manager.cpp:63: warning: "RP_FUNCTION_GENERATOR_MACRO" redefined
 #define RP_FUNCTION_GENERATOR_MACRO(r, data, elem)          \
 
In file included from /home/pmm1g15/REFPROP-manager/src/manager.cpp:5:
/home/pmm1g15/REFPROP-manager/include/REFPROP-manager/REFPROP-manager.hpp:123: note: this is the location of the previous definition
 #define RP_FUNCTION_GENERATOR_MACRO(r, data, elem)          \
 
[ 71%] Building C object CMakeFiles/refpropmanager.dir/externals/manyso/externals/MemoryModule/MemoryModule.c.o
/home/pmm1g15/REFPROP-manager/externals/manyso/externals/MemoryModule/MemoryModule.c:33:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/refpropmanager.dir/externals/manyso/externals/MemoryModule/MemoryModule.c.o] Error 1
gmake[1]: *** [CMakeFiles/refpropmanager.dir/all] Error 2
gmake: *** [all] Error 2
```

Thanks again for your help.

**Comment by ianhbell** [comment]
Sorry about that - I just squashed a number of bugs for linux compilation.  Seems it has been a while since I compiled the manager for linux.  Should work now I think.  Please let me know if not.

For OSX, yes, so far as I can make out this is a limitation of the operating system that cannot be worked around, though the manager should work on windows and linux.

**Comment by pmiquelm** [comment]
Sorry for the late reply, yes, the linux compilation was all fine. Now I just have to get it working with Matlab and fmincon's parallel funcitonality...
