### ISSUE TITLE
ERROR: Pristine option not supported on windows

### ISSUE THREAD

**Issue by Hanushan** [usnistgov/REFPROP-manager#5]
Hi,

Thank you very much for the refprop mananger.

If i try to run the manager in the debug modus i get the following error (see screenshot):

![grafik](https://user-images.githubusercontent.com/61966569/76199035-6bb01000-61ef-11ea-9765-6a7ec8308a4b.png)

How can i solve this problem?

Kind regards,
Hanny

**Comment by ianhbell** [comment]
Hanny, Can you debug into the call to ``construct_handle`` and see why it calls ``load_library_pristine``? Maybe I have left something in there from debugging on my side?

**Comment by ianhbell** [comment]
Here's the problem: https://github.com/usnistgov/REFPROP-manager/blob/master/include/REFPROP-manager/REFPROP-manager.hpp#L88 .  Change the LOAD_LIBRARY_PRISTINE to LOAD_FILE, that should do it I hope.

**Comment by Hanushan** [comment]
Hi Ian, thank you very much. That solved the problem. 
I still have on Issue: In test2.cpp the Fluid is not changed during the calculation. Can you confirm that? 

During the debuggin i could detect that always the same values are calculated without taking the different fluid into account.

**Comment by ianhbell** [comment]
Did you do ``LOAD_LIBRARY`` rather than ``LOAD_FILE``? If so, for ``LOAD_LIBRARY`` each instance is actually pointing to the same instance in memory.  Recommend that you print out the critical temperature for each instance to make sure that it has been setup properly.

**Comment by Hanushan** [comment]
My mistake! Thank you

**Comment by Hanushan** [comment]
solved
