### ISSUE TITLE
REFPROP-manager.hpp glitch in Windows

### ISSUE THREAD

**Issue by bibiloi1** [usnistgov/REFPROP-manager#7]
REFPROP-manager,hpp has a glitch when building under Windows (Windows 10 with CMake 3.18 and using Visual Studio 2019 as generator)
Line 88 reads:
     auto load_method = AbstractSharedLibraryWrapper::load_method::LOAD_LIBRARY_PRISTINE;

but LOAD_LIBRARY_PRISTINE throws in windows.h. Under windows use LOAD_LIBRARY instead.
Best regards,
Felix Oltean
Gas & Oil Know-How SRL, Medias, Romania

**Comment by ianhbell** [comment]
This time I really moved it to the correct repository.

**Comment by ianhbell** [comment]
I think we can probably close this one with my fix.  Please let me know.  But really, it would be better to allow you to specify that as argument to REFPROPInstance.  I'll see about a good way to make that change.

**Comment by bibiloi1** [comment]
Sure, we can close the issue. I think a good way to fix it would be to change the option from LOAD_LIBRARY_PRISTINE to LOAD_LIBRARY behind the scene for Windows because Windows just does not implement LOAD_LIBRARY_PRISTINE. It's up to you as developer.

**Comment by ianhbell** [comment]
Did you check my commit :) ?  That's precisely what I did, except I did the load from file.

**Comment by bibiloi1** [comment]
Great! Sorry, I didn't check the commit first. I'm really submerged into fitting this libraries in a tiny industrial computer

**Comment by ianhbell** [comment]
Please open an issue here if you run into trouble. I'd like to resolve any issues that come up.
