### ISSUE TITLE
how to use it on linux

### ISSUE THREAD

**Issue by forestmojo** [usnistgov/REFPROP-manager#8]
hi,

Is there more information about how to create library file on linux?
thanks a lot for your help.

**Comment by ianhbell** [comment]
Follow the instructions from here: https://github.com/usnistgov/REFPROP-manager#cmake-build

Only change is to drop the generator, the default should be fine.  So that would be:

```
git clone --recursive https://github.com/usnistgov/REFPROP-manager
cd REFPROP-manager
mkdir build
cd build
cmake ..
cmake --build . --config Release
```

**Comment by ianhbell** [comment]
Or, what is your question?

**Comment by forestmojo** [comment]
I would like to call REFPROP 's library in python under linux system. so I have to compile the source to generate the so file. As example like following, I should replace windows dll file with linux so file. Am I right?
Have you tried this before successfully?

```python
# Get this Python module from https://github.com/usnistgov/REFPROP-wrappers/wrappers/python
import ctREFPROP.ctREFPROP as ct
# Absolute path to the folder that has a copy of REFPROP compiled 
# with dynamic linkage of the runtimes
path = r"D:\Code\REFPROP-cmake\build\10dyn\Release" 
# A "conventional" copy of the REFPROP dll
RP1 = ct.REFPROPFunctionLibrary(path, "dll")
# Now the magic starts... This is a Python wrapper of the manager shared library
manager = ct.REFPROPLibraryManager(r'D:\Code\REFPROP-manager\msvc\Release\REFMAN64.dll')
# Here is a copy of REFPROP that is loaded into the manager.  Internally, the handle
# is cached for subsequent calls into the DLL
RP2 = manager.get_instance(path,"REFPRP64.dll")
for RP in RP1,RP2:
    baseSI = RP.GETENUMdll(0, "MOLAR BASE SI  ").iEnum
    iMass = 0; iFlag = 0
    r = RP.REFPROPdll(r"AMMONIA.FLD", "TD","ETA",baseSI,iMass,iFlag,398.788,7044.7,[1.0]+[0.0]*19) 
print(r)  
```

**Comment by ianhbell** [comment]
You need to build "normal" REFPROP with : https://github.com/usnistgov/REFPROP-cmake 

Then build REFPROP-manager with this repo.  Are you sure you need the manager and not just normal REFPROP?
