### ISSUE TITLE
error : downloading 'https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2' failed

### ISSUE THREAD

**Issue by xanthatedalkyle** [usnistgov/REFPROP-manager#9]
can't seem to be able to download boost to build REFPROP-manager.
Here is the log : 
Checking Build System
  Creating directories for 'boost-populate'
  Building Custom Rule C:/Users/ro_he/REFPROP-manager/build/_deps/boost-subbuild/CMakeLists.txt
  Performing download step (download, verify and extract) for 'boost-populate'
  -- Downloading...
     dst='C:/Users/ro_he/REFPROP-manager/build/_deps/boost-subbuild/boost-populate-prefix/src/boost_1_71_0.tar.bz2'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2'
  -- [download 0% complete]
  CMake Error at boost-subbuild/boost-populate-prefix/src/boost-populate-stamp/download-boost-populate.cmake:170 (message):
    Each download failed!

CUSTOMBUILD : error : downloading 'https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2' failed [C:\Users\ro_he\REFPROP-manager\build\_deps\boost-subbuild\boost-populate.vcxproj]
            status_code: 22
            status_string: "HTTP response code said error"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 44.238.54.15:443...

    Connected to dl.bintray.com (44.238.54.15) port 443 (#0)

    schannel: disabled automatic use of client certificate

    schannel: ALPN, offering h2

    schannel: ALPN, offering http/1.1

    ALPN, server did not agree to a protocol

    GET /boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2 HTTP/1.1

    Host: dl.bintray.com

    User-Agent: curl/7.77.0

    Accept: */*

    Mark bundle as not supporting multiuse

    HTTP/1.1 403 Forbidden

    Server: nginx

    Date: Fri, 30 Jul 2021 12:46:18 GMT

    Content-Type: text/plain

    Content-Length: 10

    Connection: keep-alive

    ETag: "57a86fed-a"

CUSTOMBUILD : The requested URL returned error : 403 [C:\Users\ro_he\REFPROP-manager\build\_deps\boost-subbuild\boost-populate.vcxproj]

    Closing connection 0

    schannel: shutting down SSL/TLS connection with dl.bintray.com port 443

            --- LOG END ---

How can I solve that please ?

**Comment by ianhbell** [comment]
bintray has been deprecated, and boost-cmake was updated to fix the path, and I pushed an update to the submodule pulling in the fix.

**Comment by ianhbell** [comment]
So please try again, it should work now I think.

**Comment by xanthatedalkyle** [comment]
thank you very much!
